### ISSUE TITLE
git repository lack tags corresponding with CPAN releases.

### ISSUE THREAD

**Issue by jonassmedegaard** [Aneurysm9/hostfile_manager#5]
Hi,

Please consider taging CPAN releases as git tags.  That helps those wanting correlate CPAN releases with atomic git commits, e.g. those (like me, for Debian) redistributing your nice project.

**Comment by Aneurysm9** [comment]
I've added tags at what I believe are the commits corresponding to the CPAN releases.  Let me know if anything seems off.

**Comment by jonassmedegaard** [comment]
Quoting Anthony Mirabella (2018-12-23 07:35:26)
> I've added tags at what I believe are the commits corresponding to the CPAN releases.  Let me know if anything seems off.

Thanks!

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
