### ISSUE TITLE
email identifer possibly outdated

### ISSUE THREAD

**Issue by jonassmedegaard** [Aneurysm9/hostfile_manager#7]
It seems from recent git commits that your email address has changed from gmail.com in 2011 (through synacor.com in 2015) to aneurysm9.com here in 2018.

Perhaps that calls for updating author info in POD entries of code, and extending author info in CPAN metadata to include that identifier?

**Comment by Aneurysm9** [comment]
Thanks for taking the time to open these issues.  I appreciate that someone is thinking about QOL issues for users.  With this one, the listed email address is still valid and I expect will continue to be indefinitely, so I will leave it as is.
